---
- name: Create the /etc/sysctl.d directory (if necessary)
  ansible.builtin.file:
    mode: 0755
    path: /etc/sysctl.d
    state: directory

- name: Copy sysctl file
  ansible.builtin.copy:
    dest: /etc/sysctl.d/99-more_ephemeral_ports.conf
    mode: 0644
    src: more_ephemeral_ports.conf
